---
- hosts: localhost
  gather_facts: yes

  tasks:
  - name: install jq
    sudo: yes
    apt: name=jq update_cache=yes force=yes

  - name: install wget
    sudo: yes
    apt: name=wget update_cache=no force=yes 

  - name: install nginx 
    sudo: yes
    apt: name=nginx update_cache=no force=yes



